// @ts-nocheck
// deno-lint-ignore-file
// GENERATED FILE — DO NOT EDIT DIRECTLY
// Generated by 'deno task bundle:plugin' from plugins/agy-bridge.plugin.ts
// Source of truth: plugins/agy-bridge-helpers.ts

// plugins/agy-bridge-helpers.ts
var MODEL_MAP_VERSION = 2;
var FALLBACK_MODELS = [
  "gemini-3.7-flash-high",
  "gemini-3.7-flash-medium",
  "gemini-3.7-flash-low",
  "gemini-3.6-flash-high",
  "gemini-3.6-flash-medium",
  "gemini-3.6-flash-low",
  "gemini-3.1-pro-high",
  "gemini-3.1-pro-low",
  "claude-sonnet-4-6",
  "claude-opus-4-6-thinking",
  "gpt-oss-120b-medium",
  "gemini-3.8-flash-high",
  "gemini-3.8-flash-medium",
  "gemini-3.8-flash-low"
];
var EFFORT_SUFFIXES = [
  "high",
  "medium",
  "low",
  "thinking"
];
function stripEffortSuffix(slug, extraSuffixes) {
  const suffixes = extraSuffixes ? [
    ...EFFORT_SUFFIXES,
    ...extraSuffixes
  ] : EFFORT_SUFFIXES;
  for (const suffix of suffixes) {
    const needle = `-${suffix}`;
    if (slug.endsWith(needle)) {
      return {
        base: slug.slice(0, -needle.length),
        variant: suffix
      };
    }
  }
  return {
    base: slug
  };
}
function groupBases(slugs) {
  const map = /* @__PURE__ */ new Map();
  const unassigned = [];
  for (const slug of slugs) {
    const { base, variant } = stripEffortSuffix(slug);
    if (variant) {
      if (!map.has(base)) map.set(base, /* @__PURE__ */ new Set());
      map.get(base).add(variant);
    } else {
      unassigned.push(slug);
    }
  }
  const remaining = [];
  for (const slug of unassigned) {
    let matched = false;
    for (const knownBase of map.keys()) {
      if (slug.startsWith(`${knownBase}-`)) {
        const variant = slug.slice(knownBase.length + 1);
        if (variant && !variant.includes("/")) {
          map.get(knownBase).add(variant);
          matched = true;
          break;
        }
      }
    }
    if (!matched) {
      remaining.push(slug);
    }
  }
  const prefixMap = /* @__PURE__ */ new Map();
  for (const slug of remaining) {
    const lastDash = slug.lastIndexOf("-");
    if (lastDash > 0) {
      const baseCandidate = slug.slice(0, lastDash);
      const variantCandidate = slug.slice(lastDash + 1);
      if (/^[a-zA-Z]+$/.test(variantCandidate)) {
        if (!prefixMap.has(baseCandidate)) prefixMap.set(baseCandidate, []);
        prefixMap.get(baseCandidate).push(slug);
      }
    }
  }
  const finalRemaining = new Set(remaining);
  for (const [baseCandidate, group] of prefixMap.entries()) {
    if (group.length > 1) {
      if (!map.has(baseCandidate)) map.set(baseCandidate, /* @__PURE__ */ new Set());
      for (const slug of group) {
        const variant = slug.slice(baseCandidate.length + 1);
        map.get(baseCandidate).add(variant);
        finalRemaining.delete(slug);
      }
    }
  }
  for (const slug of finalRemaining) {
    if (!map.has(slug)) map.set(slug, /* @__PURE__ */ new Set());
  }
  return map;
}
function buildModelMap(bases) {
  const out = {};
  for (const [base, variants] of bases) {
    for (const profile of [
      "ro",
      "rw"
    ]) {
      const id = `auto-${profile}-${base}`;
      const variantMap = {};
      for (const v of variants) variantMap[v] = {
        reasoningEffort: v
      };
      out[id] = {
        id,
        name: id,
        provider: {
          id: "agy-bridge",
          name: "AGY Bridge"
        },
        ...variants.size ? {
          reasoning: true,
          interleaved: {
            field: "reasoning_content"
          }
        } : {},
        variants: variantMap
      };
    }
  }
  return out;
}

// plugins/agy-bridge.plugin.ts
async function resolveSlugs(authKey) {
  try {
    const headers = {};
    if (authKey) headers["Authorization"] = `Bearer ${authKey}`;
    const res = await fetch("http://127.0.0.1:7421/v1/models", {
      headers
    });
    if (!res.ok) throw new Error(`GET /v1/models ${res.status}`);
    const data = await res.json();
    const ids = (data.data ?? []).map((m) => m.id).filter(Boolean);
    if (ids.length) return ids;
    throw new Error("empty");
  } catch {
    return [
      ...FALLBACK_MODELS
    ];
  }
}
var AgyBridgePlugin = (_input) => {
  return Promise.resolve({
    auth: {
      provider: "agy-bridge",
      loader: (auth) => {
        if (auth?.type === "api" && auth.key) {
          return Promise.resolve({
            apiKey: auth.key
          });
        }
        return Promise.resolve({});
      },
      methods: [
        {
          type: "api",
          label: "AGY Token (paste from ~/.config/agy-bridge/env)"
        }
      ]
    },
    provider: {
      id: "agy-bridge",
      models: async (_provider, ctx) => {
        const key = ctx.auth?.key;
        const slugs = await resolveSlugs(key);
        const grouped = groupBases(slugs);
        return buildModelMap(grouped);
      }
    }
  });
};
var agy_bridge_plugin_default = AgyBridgePlugin;
export {
  FALLBACK_MODELS,
  MODEL_MAP_VERSION,
  buildModelMap,
  agy_bridge_plugin_default as default,
  groupBases
};
