// @ts-nocheck
// deno-lint-ignore-file
// GENERATED FILE — DO NOT EDIT DIRECTLY
// Generated by 'deno task bundle:plugin:v2' from plugins/agy-bridge.v2.ts
// Source of truth: plugins/agy-bridge-helpers.ts
// '@opencode/plugin' is intentionally left external: the OpenCode V2 runtime
// resolves it, and the repo's copy is a type-only shim.

// plugins/agy-bridge.v2.ts
import { Plugin } from "@opencode/plugin";

// plugins/agy-bridge-helpers.ts
var FALLBACK_MODELS = [
  "gemini-3.7-flash-high",
  "gemini-3.7-flash-medium",
  "gemini-3.7-flash-low",
  "gemini-3.6-flash-high",
  "gemini-3.6-flash-medium",
  "gemini-3.6-flash-low",
  "gemini-3.1-pro-high",
  "gemini-3.1-pro-low",
  "claude-sonnet-4-6",
  "claude-opus-4-6-thinking",
  "gpt-oss-120b-medium",
  "gemini-3.8-flash-high",
  "gemini-3.8-flash-medium",
  "gemini-3.8-flash-low"
];
var EFFORT_SUFFIXES = [
  "high",
  "medium",
  "low",
  "thinking"
];
function stripEffortSuffix(slug, extraSuffixes) {
  const suffixes = extraSuffixes ? [
    ...EFFORT_SUFFIXES,
    ...extraSuffixes
  ] : EFFORT_SUFFIXES;
  for (const suffix of suffixes) {
    const needle = `-${suffix}`;
    if (slug.endsWith(needle)) {
      return {
        base: slug.slice(0, -needle.length),
        variant: suffix
      };
    }
  }
  return {
    base: slug
  };
}
function groupBases(slugs) {
  const map = /* @__PURE__ */ new Map();
  const unassigned = [];
  for (const slug of slugs) {
    const { base, variant } = stripEffortSuffix(slug);
    if (variant) {
      if (!map.has(base)) map.set(base, /* @__PURE__ */ new Set());
      map.get(base).add(variant);
    } else {
      unassigned.push(slug);
    }
  }
  const remaining = [];
  for (const slug of unassigned) {
    let matched = false;
    for (const knownBase of map.keys()) {
      if (slug.startsWith(`${knownBase}-`)) {
        const variant = slug.slice(knownBase.length + 1);
        if (variant && !variant.includes("/")) {
          map.get(knownBase).add(variant);
          matched = true;
          break;
        }
      }
    }
    if (!matched) {
      remaining.push(slug);
    }
  }
  const prefixMap = /* @__PURE__ */ new Map();
  for (const slug of remaining) {
    const lastDash = slug.lastIndexOf("-");
    if (lastDash > 0) {
      const baseCandidate = slug.slice(0, lastDash);
      const variantCandidate = slug.slice(lastDash + 1);
      if (/^[a-zA-Z]+$/.test(variantCandidate)) {
        if (!prefixMap.has(baseCandidate)) prefixMap.set(baseCandidate, []);
        prefixMap.get(baseCandidate).push(slug);
      }
    }
  }
  const finalRemaining = new Set(remaining);
  for (const [baseCandidate, group] of prefixMap.entries()) {
    if (group.length > 1) {
      if (!map.has(baseCandidate)) map.set(baseCandidate, /* @__PURE__ */ new Set());
      for (const slug of group) {
        const variant = slug.slice(baseCandidate.length + 1);
        map.get(baseCandidate).add(variant);
        finalRemaining.delete(slug);
      }
    }
  }
  for (const slug of finalRemaining) {
    if (!map.has(slug)) map.set(slug, /* @__PURE__ */ new Set());
  }
  return map;
}
var MODEL_PROFILES = [
  "ro",
  "rw"
];
function modelID(base, profile) {
  return `auto-${profile}-${base}`;
}
function reasoningEffortFor(effort) {
  return effort === "thinking" ? "max" : effort;
}
function eachModelProfile(bases, emit) {
  for (const [base, variants] of bases) {
    for (const profile of MODEL_PROFILES) {
      emit({
        id: modelID(base, profile),
        base,
        profile,
        efforts: [
          ...variants
        ]
      });
    }
  }
}
var V2_PROVIDER_ID = "agy-bridge";
var V2_REASONING_FIELD = "reasoning_content";
var V2_CAPABILITIES = {
  tools: true,
  input: [
    "text",
    "image"
  ],
  output: [
    "text"
  ]
};
var V2_LIMIT = {
  context: 2e5,
  output: 32e3
};
function buildModelV2(bases) {
  const models = [];
  eachModelProfile(bases, ({ id, efforts }) => {
    models.push({
      id,
      providerID: V2_PROVIDER_ID,
      name: id,
      enabled: true,
      capabilities: {
        ...V2_CAPABILITIES,
        input: [
          ...V2_CAPABILITIES.input
        ],
        output: [
          ...V2_CAPABILITIES.output
        ]
      },
      limit: {
        ...V2_LIMIT
      },
      compatibility: {
        reasoningField: V2_REASONING_FIELD
      },
      variants: [
        ...efforts
      ].sort().map((effort) => ({
        id: effort,
        settings: {
          reasoningEffort: reasoningEffortFor(effort)
        }
      }))
    });
  });
  models.sort((a, b) => a.id < b.id ? -1 : a.id > b.id ? 1 : 0);
  return models;
}
function declaredVariantsByModel(bases) {
  const out = /* @__PURE__ */ new Map();
  eachModelProfile(bases, ({ id, efforts }) => out.set(id, new Set(efforts)));
  return out;
}
function filterUndeclaredVariants(variants, declared) {
  if (!Array.isArray(variants)) return [];
  if (!declared) return [
    ...variants
  ];
  return variants.filter((variant) => declared.has(variant.id));
}

// plugins/agy-bridge.v2.ts
var PROVIDER_ID = "agy-bridge";
var BRIDGE_MODELS_URL = "http://127.0.0.1:7421/v1/models";
var BRIDGE_BASE_URL = "http://127.0.0.1:7421/v1";
async function resolveSlugs(authKey) {
  try {
    const headers = {};
    if (authKey) headers["Authorization"] = `Bearer ${authKey}`;
    const res = await fetch(BRIDGE_MODELS_URL, {
      headers
    });
    if (!res.ok) throw new Error(`GET /v1/models ${res.status}`);
    const data = await res.json();
    const ids = (data.data ?? []).map((m) => m.id).filter(Boolean);
    if (ids.length) return ids;
    throw new Error("empty");
  } catch {
    return [
      ...FALLBACK_MODELS
    ];
  }
}
function extractKey(credential) {
  if (typeof credential === "string" && credential) return credential;
  if (typeof credential === "object" && credential !== null) {
    const rec = credential;
    for (const k of [
      "key",
      "apiKey",
      "token"
    ]) {
      if (typeof rec[k] === "string" && rec[k]) {
        return rec[k];
      }
    }
  }
  return void 0;
}
function buildV2Models(slugs) {
  return buildModelV2(groupBases(slugs));
}
function providerInfo() {
  return {
    id: PROVIDER_ID,
    name: "AGY Bridge",
    activation: "enabled",
    package: "@opencode/ai/providers/openai-compatible",
    settings: {
      baseURL: BRIDGE_BASE_URL
    }
  };
}
var plugin = Plugin.define({
  id: PROVIDER_ID,
  async setup(ctx) {
    const state = {
      slugs: [
        ...FALLBACK_MODELS
      ],
      declared: declaredVariantsByModel(groupBases(FALLBACK_MODELS))
    };
    const loadSlugs = async () => {
      let key;
      try {
        const connection = await ctx.integration.connection.active(PROVIDER_ID);
        if (connection) {
          const credential = await ctx.integration.connection.resolve(connection);
          key = extractKey(credential);
        }
      } catch {
        key = void 0;
      }
      state.slugs = await resolveSlugs(key);
      state.declared = declaredVariantsByModel(groupBases(state.slugs));
    };
    await loadSlugs();
    await ctx.integration.transform((editor) => {
      editor.method.update({
        integrationID: PROVIDER_ID,
        method: {
          id: "api",
          type: "api-key",
          label: "AGY Token (paste from ~/.config/agy-bridge/env)"
        }
      });
    });
    await ctx.provider.transform((editor) => {
      editor.add({
        info: providerInfo(),
        models: buildV2Models(state.slugs)
      });
    });
    await ctx.model.transform((editor) => {
      for (const model of editor.list(PROVIDER_ID)) {
        const allowed = state.declared.get(model.id);
        if (!allowed || !Array.isArray(model.variants)) continue;
        const kept = filterUndeclaredVariants(model.variants, allowed);
        if (kept.length === model.variants.length) continue;
        editor.update(PROVIDER_ID, model.id, (draft) => {
          draft.variants = kept;
        });
      }
    });
    const refresh = async () => {
      await loadSlugs();
      await ctx.provider.reload();
      await ctx.model.reload();
    };
    const timer = setInterval(() => {
      void refresh().catch((err) => console.error("[agy-bridge.v2] refresh:", err));
    }, refreshIntervalMs(ctx));
    return () => clearInterval(timer);
  }
});
var REFRESH_INTERVAL_MS = 6e4;
function refreshIntervalMs(ctx) {
  const requested = ctx.options?.refreshIntervalMs;
  return typeof requested === "number" && requested > 0 ? requested : REFRESH_INTERVAL_MS;
}
var agy_bridge_v2_default = plugin;
export {
  BRIDGE_BASE_URL,
  BRIDGE_MODELS_URL,
  PROVIDER_ID,
  REFRESH_INTERVAL_MS,
  buildV2Models,
  agy_bridge_v2_default as default,
  providerInfo,
  refreshIntervalMs,
  resolveSlugs
};
