// @ts-nocheck
// deno-lint-ignore-file
// GENERATED FILE — DO NOT EDIT DIRECTLY
// Generated by 'deno task bundle:plugin' from plugins/agy-bridge.plugin.ts
// Source of truth: plugins/agy-bridge-helpers.ts

// plugins/agy-bridge-helpers.ts
var FALLBACK_MODELS = [
  "gemini-3.7-flash-high",
  "gemini-3.7-flash-medium",
  "gemini-3.7-flash-low",
  "gemini-3.6-flash-high",
  "gemini-3.6-flash-medium",
  "gemini-3.6-flash-low",
  "gemini-3.1-pro-high",
  "gemini-3.1-pro-low",
  "claude-sonnet-4-6",
  "claude-opus-4-6-thinking",
  "gpt-oss-120b-medium",
  "gemini-3.8-flash-high",
  "gemini-3.8-flash-medium",
  "gemini-3.8-flash-low"
];
var EFFORT_SUFFIXES = [
  "high",
  "medium",
  "low",
  "thinking"
];
function stripEffortSuffix(slug, extraSuffixes) {
  const suffixes = extraSuffixes ? [
    ...EFFORT_SUFFIXES,
    ...extraSuffixes
  ] : EFFORT_SUFFIXES;
  for (const suffix of suffixes) {
    const needle = `-${suffix}`;
    if (slug.endsWith(needle)) {
      return {
        base: slug.slice(0, -needle.length),
        variant: suffix
      };
    }
  }
  return {
    base: slug
  };
}
function groupBases(slugs) {
  const map = /* @__PURE__ */ new Map();
  const unassigned = [];
  for (const slug of slugs) {
    const { base, variant } = stripEffortSuffix(slug);
    if (variant) {
      if (!map.has(base)) map.set(base, /* @__PURE__ */ new Set());
      map.get(base).add(variant);
    } else {
      unassigned.push(slug);
    }
  }
  const remaining = [];
  for (const slug of unassigned) {
    let matched = false;
    for (const knownBase of map.keys()) {
      if (slug.startsWith(`${knownBase}-`)) {
        const variant = slug.slice(knownBase.length + 1);
        if (variant && !variant.includes("/")) {
          map.get(knownBase).add(variant);
          matched = true;
          break;
        }
      }
    }
    if (!matched) {
      remaining.push(slug);
    }
  }
  const prefixMap = /* @__PURE__ */ new Map();
  for (const slug of remaining) {
    const lastDash = slug.lastIndexOf("-");
    if (lastDash > 0) {
      const baseCandidate = slug.slice(0, lastDash);
      const variantCandidate = slug.slice(lastDash + 1);
      if (/^[a-zA-Z]+$/.test(variantCandidate)) {
        if (!prefixMap.has(baseCandidate)) prefixMap.set(baseCandidate, []);
        prefixMap.get(baseCandidate).push(slug);
      }
    }
  }
  const finalRemaining = new Set(remaining);
  for (const [baseCandidate, group] of prefixMap.entries()) {
    if (group.length > 1) {
      if (!map.has(baseCandidate)) map.set(baseCandidate, /* @__PURE__ */ new Set());
      for (const slug of group) {
        const variant = slug.slice(baseCandidate.length + 1);
        map.get(baseCandidate).add(variant);
        finalRemaining.delete(slug);
      }
    }
  }
  for (const slug of finalRemaining) {
    if (!map.has(slug)) map.set(slug, /* @__PURE__ */ new Set());
  }
  return map;
}
function wireModel(base, variant) {
  return variant ? `${base}-${variant}` : base;
}
function buildModelMap(bases) {
  const out = {};
  for (const [base, variants] of bases) {
    for (const profile of [
      "ro",
      "rw"
    ]) {
      const id = `auto-${profile}-${base}`;
      const variantMap = {};
      for (const v of variants) variantMap[v] = {
        reasoningEffort: v
      };
      out[id] = {
        id,
        name: id,
        provider: {
          id: "agy-bridge",
          name: "AGY Bridge"
        },
        ...variants.size ? {
          reasoning: true,
          interleaved: {
            field: "reasoning_content"
          }
        } : {},
        variants: variantMap
      };
    }
  }
  return out;
}

// plugins/agy-bridge.plugin.ts
async function resolveSlugs(authKey) {
  try {
    const headers = {};
    if (authKey) headers["Authorization"] = `Bearer ${authKey}`;
    const res = await fetch("http://127.0.0.1:7421/v1/models", {
      headers
    });
    if (!res.ok) throw new Error(`GET /v1/models ${res.status}`);
    const data = await res.json();
    const ids = (data.data ?? []).map((m) => m.id).filter(Boolean);
    if (ids.length) return ids;
    throw new Error("empty");
  } catch {
    return [
      ...FALLBACK_MODELS
    ];
  }
}
var FALLBACK_GROUPED = groupBases([
  ...FALLBACK_MODELS
]);
var variantByModel = /* @__PURE__ */ new Map();
function defaultVariantForBase(base) {
  const variants = FALLBACK_GROUPED.get(base);
  if (!variants || variants.size === 0) return void 0;
  if (variants.has("medium")) return "medium";
  if (variants.has("high")) return "high";
  if (variants.has("low")) return "low";
  if (variants.has("thinking")) return "thinking";
  return Array.from(variants)[0];
}
function installFetchWrapper() {
  const g = globalThis;
  if (g.__agy_bridge_fetch_patched) return;
  g.__agy_bridge_fetch_patched = true;
  const origFetch = globalThis.fetch.bind(globalThis);
  globalThis.fetch = async (input, init) => {
    try {
      const urlStr = typeof input === "string" ? input : input instanceof URL ? input.toString() : input.url ?? String(input);
      const isTarget = urlStr.includes("127.0.0.1:7421/v1/chat/completions") || urlStr.includes("localhost:7421/v1/chat/completions") || urlStr.includes("127.0.0.1:7421/chat/completions") || urlStr.includes("localhost:7421/chat/completions");
      if (isTarget) {
        let bodyStr;
        let bodyObj;
        let isRequestBody = false;
        if (init?.body && typeof init.body === "string") {
          bodyStr = init.body;
        } else if (input instanceof Request) {
          try {
            const cloned = input.clone();
            bodyStr = await cloned.text();
            isRequestBody = true;
          } catch {
            bodyStr = void 0;
          }
        }
        if (bodyStr) {
          try {
            bodyObj = JSON.parse(bodyStr);
          } catch {
            bodyObj = void 0;
          }
        }
        if (bodyObj && typeof bodyObj === "object") {
          const modelRaw = String(bodyObj.model ?? "");
          const variantRaw = bodyObj.variant ? String(bodyObj.variant) : void 0;
          const storedVariant = variantByModel.get(modelRaw) || (typeof bodyObj.model === "string" ? variantByModel.get(String(bodyObj.model)) : void 0);
          const effectiveVariant = variantRaw && variantRaw !== "default" ? variantRaw : storedVariant;
          let shouldRewrite = false;
          let wired;
          if (effectiveVariant && effectiveVariant !== "default") {
            wired = wireModel(modelRaw, effectiveVariant);
            shouldRewrite = true;
          } else {
            const match = modelRaw.match(/^auto-(ro|rw)-(.+)$/);
            if (match) {
              const basePart = match[2];
              const hasSuffix = EFFORT_SUFFIXES.some((s) => basePart.endsWith(`-${s}`));
              if (!hasSuffix) {
                const def = defaultVariantForBase(basePart);
                if (def) {
                  wired = wireModel(modelRaw, def);
                  shouldRewrite = true;
                }
              }
            }
          }
          if (shouldRewrite && wired) {
            bodyObj.model = wired;
            if ("variant" in bodyObj) delete bodyObj.variant;
            const newBody = JSON.stringify(bodyObj);
            if (isRequestBody && input instanceof Request) {
              const newReq = new Request(input.url, {
                method: input.method,
                headers: input.headers,
                body: newBody
              });
              return origFetch(newReq, init);
            } else if (init) {
              const newInit = {
                ...init,
                body: newBody
              };
              if (newInit.headers) {
                const h = new Headers(newInit.headers);
                h.delete("content-length");
                newInit.headers = h;
              }
              return origFetch(input, newInit);
            } else {
              return origFetch(input, {
                method: "POST",
                body: newBody,
                headers: {
                  "content-type": "application/json"
                }
              });
            }
          }
        }
      }
    } catch (_err) {
    }
    return origFetch(input, init);
  };
}
var AgyBridgePlugin = (_input) => {
  installFetchWrapper();
  return Promise.resolve({
    auth: {
      provider: "agy-bridge",
      loader: (auth) => {
        if (auth?.type === "api" && auth.key) {
          return Promise.resolve({
            apiKey: auth.key
          });
        }
        return Promise.resolve({});
      },
      methods: [
        {
          type: "api",
          label: "AGY Token (paste from ~/.config/agy-bridge/env)"
        }
      ]
    },
    provider: {
      id: "agy-bridge",
      models: async (_provider, ctx) => {
        const key = ctx.auth?.key;
        const slugs = await resolveSlugs(key);
        const grouped = groupBases(slugs);
        return buildModelMap(grouped);
      }
    },
    "chat.message": (input) => {
      try {
        if (input.variant && input.model?.modelID) {
          variantByModel.set(input.model.modelID, input.variant);
        }
      } catch (_err) {
      }
      return Promise.resolve();
    }
  });
};
var agy_bridge_plugin_default = AgyBridgePlugin;
export {
  FALLBACK_MODELS,
  buildModelMap,
  agy_bridge_plugin_default as default,
  groupBases
};
