/**
 * scripts/bundle-plugin.ts
 * Bundles plugins/agy-bridge.plugin.ts into plugins/agy-bridge.ts atomically
 * with '// @ts-nocheck' and GENERATED banner prepended.
 */
const banner = `// @ts-nocheck
// deno-lint-ignore-file
// GENERATED FILE — DO NOT EDIT DIRECTLY
// Generated by 'deno task bundle:plugin' from plugins/agy-bridge.plugin.ts
// Source of truth: plugins/agy-bridge-helpers.ts

`;

const tempBundle = await Deno.makeTempFile({
  prefix: "agy-bundle-",
  suffix: ".js",
});
try {
  const cmd = new Deno.Command(Deno.execPath(), {
    args: ["bundle", "plugins/agy-bridge.plugin.ts", "-o", tempBundle],
    stdout: "piped",
    stderr: "piped",
  });
  const output = await cmd.output();
  if (!output.success) {
    const err = new TextDecoder().decode(output.stderr);
    throw new Error(`deno bundle failed: ${err}`);
  }

  const bundledCode = await Deno.readTextFile(tempBundle);
  const finalContent = banner + bundledCode;

  const tempFinal = await Deno.makeTempFile({
    dir: "plugins",
    prefix: "agy-bridge.ts.tmp-",
  });
  await Deno.writeTextFile(tempFinal, finalContent);
  await Deno.rename(tempFinal, "plugins/agy-bridge.ts");
} finally {
  try {
    await Deno.remove(tempBundle);
  } catch {
    // Ignore cleanup error
  }
}
