/**
 * scripts/bundle-plugin-v2.ts
 *
 * Bundles plugins/agy-bridge.v2.ts into plugins/agy-bridge.v2.bundle.ts,
 * atomically, with the same GENERATED banner discipline as the V1 bundle.
 *
 * Two things make the V2 bundle different from the V1 one:
 *
 * 1. `@opencode/plugin` is kept EXTERNAL (`--external`). The V2 runtime resolves
 *    that specifier itself (https://opencode.ai/v2/docs/build/plugins/cli:
 *    "OpenCode resolves this import at runtime"), so inlining the repo's local
 *    type-shim stub would ship a fake `Plugin.define` to users.
 * 2. It MUST be self-contained. V2 auto-loads *every* direct `.ts`/`.js` file in
 *    `~/.config/opencode/plugins/` (https://opencode.ai/v2/docs/plugins →
 *    "Discover"), so installing `agy-bridge.v2.ts` next to a non-bundled
 *    `agy-bridge-helpers.ts` would make the runtime load the helper module as if
 *    it were a plugin.
 */
const banner = `// @ts-nocheck
// deno-lint-ignore-file
// GENERATED FILE — DO NOT EDIT DIRECTLY
// Generated by 'deno task bundle:plugin:v2' from plugins/agy-bridge.v2.ts
// Source of truth: plugins/agy-bridge-helpers.ts
// '@opencode/plugin' is intentionally left external: the OpenCode V2 runtime
// resolves it, and the repo's copy is a type-only shim.

`;

const ENTRY = "plugins/agy-bridge.v2.ts";
const OUTPUT = "plugins/agy-bridge.v2.bundle.ts";

const tempBundle = await Deno.makeTempFile({
  prefix: "agy-bundle-v2-",
  suffix: ".js",
});
try {
  const cmd = new Deno.Command(Deno.execPath(), {
    args: [
      "bundle",
      ENTRY,
      "-o",
      tempBundle,
      "--external",
      "@opencode/plugin",
    ],
    stdout: "piped",
    stderr: "piped",
  });
  const output = await cmd.output();
  if (!output.success) {
    const err = new TextDecoder().decode(output.stderr);
    throw new Error(`deno bundle failed: ${err}`);
  }

  const bundledCode = await Deno.readTextFile(tempBundle);
  // Guard the invariant this script exists to protect: an inlined shim would
  // silently replace the runtime's Plugin.define.
  if (!bundledCode.includes('from "@opencode/plugin"')) {
    throw new Error(
      "bundle inlined '@opencode/plugin' — the runtime import must stay external",
    );
  }

  const finalContent = banner + bundledCode;

  const tempFinal = await Deno.makeTempFile({
    dir: "plugins",
    prefix: "agy-bridge.v2.bundle.ts.tmp-",
  });
  await Deno.writeTextFile(tempFinal, finalContent);
  await Deno.rename(tempFinal, OUTPUT);
} finally {
  try {
    await Deno.remove(tempBundle);
  } catch {
    // Ignore cleanup error
  }
}
